/*
create test mysql in localhost by docker
docker run -p 3306:3306 --name mysql -v $PWD/conf:/etc/mysql/conf.d -v $PWD/logs:/logs -v $PWD/data:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=123456 -d mysql:5.6
*/

CREATE DATABASE IF NOT EXISTS `blog` CHARACTER SET = 'utf8' DEFAULT COLLATE 'utf8_general_ci';

CREATE TABLE IF NOT EXISTS `blog_posts`(
    `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `name` VARCHAR(32) NOT NULL UNIQUE DEFAULT '' COMMENT '文章名称',
    `description` VARCHAR(1024) DEFAULT '' COMMENT '文章描述',
    `content` TEXT NOT NULL COMMENT '文章内容',
    `deleted_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '删除时间',
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
    PRIMARY KEY(`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='文章表';

CREATE TABLE IF NOT EXISTS `blog_tags`(
    `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `name`  VARCHAR(128) NOT NULL DEFAULT 'default' COMMENT '标签名称',
    `deleted_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '删除时间',
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
    PRIMARY KEY(`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='标签表';

/*文章标签中间表*/
CREATE TABLE IF NOT EXISTS `blog_tag＿posts`(
    `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `post_id` INT(10) UNSIGNED NOT NULL  COMMENT 'post自增主键',
    `tag_id` INT(10) UNSIGNED NOT NULL  COMMENT 'tag自增主键',
    `deleted_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '删除时间',
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
    PRIMARY KEY(`id`),
    UNIQUE KEY `post_tags` (`post_id`,`tag_id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='标签文章对应表';
